name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  repository_dispatch:
    types: [run_my_workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run:  echo "Payload field is ${{ github.event.client_payload.mydata }}"
        run:  echo "Created by ${{ github.event.author }}"
